const mongoose = require("mongoose");
const registration1 = new mongoose.Schema({
    id: { type: Number },
    random_id: { type: Number, unique:true  },
    waddress: { type: String, unique:true },
    investor: { type: String },
    investorId: { type: Number, unique:true  },
    referrerId: { type: Number },
    referrer: { type: String },
    promoterId: { type: Number },
    promoter: { type: String },
    block_timestamp: { type: String },
    transaction_id: { type: String, unique:true  },
    wallet_amount: { type: Number, default: 0 },
    is_member_count: { type: Number },
    total_member: { type: Number },
    direct_member: { type: Number, default: 0 },
    total_investment: { type: Number, default: 0 },
    vip_income: { type: Number, default: 0 },
    withdraw_vip_income: { type: Number, default: 0 },
    chk_status: { type: Number, default: 0 },
    income_status: { type: Number },
    up_level_paid: { type: Number, default: 0 },
    down_level_paid: { type: Number, default: 0 },
    with_income: { type: Number },
    vip1: { type: Number, default: 0 },
    vip1_wallet: { type: Number, default: 0 },
    vip1_income: { type: Number, default: 0 },
    vip1_reinvest_count: { type: Number, default: 0 },
    vip2: { type: Number, default: 0 },
    vip2_wallet: { type: Number, default: 0 },
    vip2_income: { type: Number, default: 0 },
    vip2_reinvest_count: { type: Number, default: 0 },
    vip3: { type: Number, default: 0 },
    vip3_wallet: { type: Number, default: 0 },
    vip3_income: { type: Number, default: 0 },
    vip3_reinvest_count: { type: Number, default: 0 },
}, { timestamps: true, collection: 'Registration1' })
module.exports = mongoose.model('Registration1', registration1);